import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../../components/Navbar";
import SessionWrapper from "../../components/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
